title: 'Public Service Week 2020'
description: Description
url: 'https://www.publicserviceweek.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css

collections:
    pswlf-2020:
        output: true
    all-workouts:
        output: true
    jobspecific-details:
        output: true
    occ:
        output: true
    pstac-2020:
        output: true
    psc-2020:
        output: true
    
resources_name: news
favicon: /images/PSW_Logo.png
google-analytics: UA-40876833-17
permalink: none
baseurl: ""
defaults:
    -
        scope:
            path: ""
        values:
            layout: page
